ALTER TABLE negotiations ADD COLUMN IF NOT EXISTS offered_price numeric(12,2) NULL;
ALTER TABLE negotiations ADD COLUMN IF NOT EXISTS buyer_message text NULL;
ALTER TABLE negotiations ADD COLUMN IF NOT EXISTS moderator_note text NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS city character varying(100) NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS address text NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS logo text NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS banner_url text NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS total_sales integer NULL DEFAULT 0;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS total_revenue numeric(12,2) NULL DEFAULT 0;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS products_count integer NULL DEFAULT 0;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS bonus_points integer NULL DEFAULT 0;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS inn character varying(20) NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS ogrn character varying(20) NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS rejection_reason text NULL;
ALTER TABLE seller_profiles ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone NULL DEFAULT now();
ALTER TABLE products ADD COLUMN IF NOT EXISTS original_price numeric(12,2) NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS article character varying(50) NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS in_stock boolean NULL DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS rating numeric(3,2) NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reviews_count integer NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS orders_count integer NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_spent numeric(12,2) NULL DEFAULT 0;
